//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using ET.Luban;

namespace ET
{
    [Config]
    public partial class EntryRandomConfigCategory: ConfigSingleton<EntryRandomConfigCategory>
    {
        private readonly List<EntryRandomConfig> _dataList;
        private readonly Dictionary<int, EntryRandomConfig> _dataMap;

        public EntryRandomConfigCategory(ByteBuf _buf)
        {
            _dataMap = new();
            _dataList = new();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                EntryRandomConfig _v;
                _v = EntryRandomConfig.DeserializeEntryRandomConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public List<EntryRandomConfig> DataList => _dataList;

        public EntryRandomConfig this[int key] => _dataMap[key];

        public bool Contain(int id)
        {
            return _dataMap.ContainsKey(id);
        }

        public Dictionary<int, EntryRandomConfig> GetAll()
        {
            return _dataMap;
        }

        public EntryRandomConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v)? v : null;
        public EntryRandomConfig Get(int key) => _dataMap[key];

        public EntryRandomConfig GetOne(int key)
        {
            if (this._dataMap is not { Count: > 0 })
            {
                return null;
            }

            return _dataMap.Values.GetEnumerator().Current;
        }

        public override void Resolve(Dictionary<Type, IConfigSingleton> tables)
        {
            foreach (var v in _dataList)
            {
                v.Resolve(tables);
            }

            PostResolve();
        }

        public override void TrimExcess()
        {
            _dataMap.TrimExcess();
            _dataList.TrimExcess();
        }

        public override string ConfigName() => nameof (EntryRandomConfig);
    }
}