//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using ET.Luban;

namespace ET
{
    public sealed partial class TaskTarget: Luban.BeanBase
    {
        public const int __ID__ = -1320388714;

        public TaskTarget(ByteBuf _buf)
        {
            Type = (TaskTargetType)_buf.ReadInt();
            TargetId = _buf.ReadInt();
            Count = _buf.ReadInt();
            PostInit();
        }

        /// <summary>
        /// 任务类型
        /// </summary>
        public TaskTargetType Type { get; }

        /// <summary>
        /// 任务目标Id
        /// </summary>
        public int TargetId { get; }

        /// <summary>
        /// 任务目标数量
        /// </summary>
        public int Count { get; }

        public static TaskTarget DeserializeTaskTarget(ByteBuf _buf)
        {
            return new TaskTarget(_buf);
        }

        public override int GetTypeId() => __ID__;

        public void Resolve(Dictionary<Type, IConfigSingleton> _tables)
        {
            PostResolve();
        }

        public override string ToString()
        {
            return "{ "
                    + "Type:" + Type + ","
                    + "TargetId:" + TargetId + ","
                    + "Count:" + Count + ","
                    + "}";
        }
    }
}