//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using ET.Luban;

namespace ET
{
    public sealed partial class TGlobalConfig: Luban.BeanBase
    {
        public const int __ID__ = 165700409;

        public TGlobalConfig(ByteBuf _buf)
        {
            BagCapacityLimit = _buf.ReadInt();
            BagCapacityStart = _buf.ReadInt();
            RouterHttpHost = _buf.ReadString();
            RouterHttpPort = _buf.ReadInt();
            AccountHost = _buf.ReadString();
            AccountPort = _buf.ReadInt();
            SessionTimeoutTime = _buf.ReadInt();
            PostInit();
        }

        /// <summary>
        /// 背包容量上限
        /// </summary>
        public int BagCapacityLimit { get; private set; }

        /// <summary>
        /// 背包起始容量
        /// </summary>
        public int BagCapacityStart { get; private set; }

        /// <summary>
        /// RouterManager地址
        /// </summary>
        public string RouterHttpHost { get; private set; }

        /// <summary>
        /// RouterManager端口
        /// </summary>
        public int RouterHttpPort { get; private set; }

        /// <summary>
        /// 账号服务器地址
        /// </summary>
        public string AccountHost { get; private set; }

        /// <summary>
        /// 账号服务器端口
        /// </summary>
        public int AccountPort { get; private set; }

        /// <summary>
        /// 连接超时时间
        /// </summary>
        public int SessionTimeoutTime { get; private set; }

        public static TGlobalConfig DeserializeTGlobalConfig(ByteBuf _buf)
        {
            return new TGlobalConfig(_buf);
        }

        public override int GetTypeId() => __ID__;

        public void Resolve(Dictionary<Type, IConfigSingleton> _tables)
        {
            PostResolve();
        }

        public override string ToString()
        {
            return "{ "
                    + "bagCapacityLimit:" + BagCapacityLimit + ","
                    + "bagCapacityStart:" + BagCapacityStart + ","
                    + "RouterHttpHost:" + RouterHttpHost + ","
                    + "RouterHttpPort:" + RouterHttpPort + ","
                    + "AccountHost:" + AccountHost + ","
                    + "AccountPort:" + AccountPort + ","
                    + "SessionTimeoutTime:" + SessionTimeoutTime + ","
                    + "}";
        }
    }
}