
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Luban;


namespace ET
{

public sealed partial class AIConfig: Luban.BeanBase
{
    public AIConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        AIConfigId = _buf.ReadInt();
        Order = _buf.ReadInt();
        Name = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);NodeParams = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); NodeParams.Add(_e0);}}
        PostInit();
    }

    public static AIConfig DeserializeAIConfig(ByteBuf _buf)
    {
        return new AIConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 所属ai
    /// </summary>
    public int AIConfigId { get; private set; }
    /// <summary>
    /// 此ai中的顺序
    /// </summary>
    public int Order { get; private set; }
    /// <summary>
    /// 节点名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 节点参数
    /// </summary>
    public System.Collections.Generic.List<int> NodeParams { get; private set; }

    public const int __ID__ = -294143606;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<Type, IConfigSingleton> _tables)
    {
        
        
        
        
        
        PostResolve();
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "aIConfigId:" + AIConfigId + ","
        + "order:" + Order + ","
        + "name:" + Name + ","
        + "nodeParams:" + Luban.StringUtil.CollectionToString(NodeParams) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}

