
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using ET.Luban;


namespace ET
{

public sealed partial class BattleLevelConfig: Luban.BeanBase
{
    public BattleLevelConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);MonsterId = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); MonsterId.Add(_e0);}}
        Name = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);EnterLevelRang = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); EnterLevelRang.Add(_e0);}}
        RewardExp = _buf.ReadInt();
        PostInit();
    }

    public static BattleLevelConfig DeserializeBattleLevelConfig(ByteBuf _buf)
    {
        return new BattleLevelConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 怪物列表
    /// </summary>
    public System.Collections.Generic.List<int> MonsterId { get; private set; }
    /// <summary>
    /// 关卡名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 准入等级范围
    /// </summary>
    public System.Collections.Generic.List<int> EnterLevelRang { get; private set; }
    /// <summary>
    /// 战斗胜利获取的经验值
    /// </summary>
    public int RewardExp { get; private set; }

    public const int __ID__ = -1369519122;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<Type, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "monsterId:" + Luban.StringUtil.CollectionToString(MonsterId) + ","
        + "name:" + Name + ","
        + "enterLevelRang:" + Luban.StringUtil.CollectionToString(EnterLevelRang) + ","
        + "rewardExp:" + RewardExp + ","
        + "}";
    }
}

}

