
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using ET.Luban;


namespace ET
{

public sealed partial class EquipConfig: Luban.BeanBase
{
    public EquipConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        EquipPosition = (EquipPosition)_buf.ReadInt();
        Role = _buf.ReadString();
        MaxHp = _buf.ReadInt();
        MaxMp = _buf.ReadInt();
        Strength = _buf.ReadInt();
        Intelligence = _buf.ReadInt();
        Agility = _buf.ReadInt();
        AD = _buf.ReadInt();
        AP = _buf.ReadInt();
        DEF = _buf.ReadInt();
        MDEF = _buf.ReadInt();
        Rate = _buf.ReadInt();
        CRI = _buf.ReadInt();
        EntryRandomId = _buf.ReadInt();
        PostInit();
    }

    public static EquipConfig DeserializeEquipConfig(ByteBuf _buf)
    {
        return new EquipConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 位置
    /// </summary>
    public EquipPosition EquipPosition { get; private set; }
    /// <summary>
    /// 职业
    /// </summary>
    public string Role { get; private set; }
    /// <summary>
    /// 生命
    /// </summary>
    public int MaxHp { get; private set; }
    /// <summary>
    /// 法力
    /// </summary>
    public int MaxMp { get; private set; }
    /// <summary>
    /// 力量
    /// </summary>
    public int Strength { get; private set; }
    /// <summary>
    /// 智力
    /// </summary>
    public int Intelligence { get; private set; }
    /// <summary>
    /// 敏捷
    /// </summary>
    public int Agility { get; private set; }
    /// <summary>
    /// 物理攻击
    /// </summary>
    public int AD { get; private set; }
    /// <summary>
    /// 法术攻击
    /// </summary>
    public int AP { get; private set; }
    /// <summary>
    /// 物理防御
    /// </summary>
    public int DEF { get; private set; }
    /// <summary>
    /// 法术防御
    /// </summary>
    public int MDEF { get; private set; }
    /// <summary>
    /// 攻击速度
    /// </summary>
    public int Rate { get; private set; }
    /// <summary>
    /// 暴击概率
    /// </summary>
    public int CRI { get; private set; }
    /// <summary>
    /// 词条随机Id
    /// </summary>
    public int EntryRandomId { get; private set; }

    public const int __ID__ = -233858190;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<Type, IConfigSingleton> _tables)
    {
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        PostResolve();
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "equipPosition:" + EquipPosition + ","
        + "role:" + Role + ","
        + "maxHp:" + MaxHp + ","
        + "maxMp:" + MaxMp + ","
        + "strength:" + Strength + ","
        + "intelligence:" + Intelligence + ","
        + "agility:" + Agility + ","
        + "aD:" + AD + ","
        + "aP:" + AP + ","
        + "dEF:" + DEF + ","
        + "mDEF:" + MDEF + ","
        + "rate:" + Rate + ","
        + "cRI:" + CRI + ","
        + "entryRandomId:" + EntryRandomId + ","
        + "}";
    }
}

}

