
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using ET.Luban;


namespace ET
{

public sealed partial class ForgeProductionConfig: Luban.BeanBase
{
    public ForgeProductionConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ItemConfigId = _buf.ReadInt();
        ProductionTime = _buf.ReadInt();
        MaterialId = _buf.ReadInt();
        MaterialCount = _buf.ReadInt();
        NeedLevel = _buf.ReadInt();
        PostInit();
    }

    public static ForgeProductionConfig DeserializeForgeProductionConfig(ByteBuf _buf)
    {
        return new ForgeProductionConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 物品Id
    /// </summary>
    public int ItemConfigId { get; private set; }
    /// <summary>
    /// 制造时间(秒)
    /// </summary>
    public int ProductionTime { get; private set; }
    /// <summary>
    /// 制造材料
    /// </summary>
    public int MaterialId { get; private set; }
    /// <summary>
    /// 制造所需的资源数量
    /// </summary>
    public int MaterialCount { get; private set; }
    /// <summary>
    /// 制造所需等级
    /// </summary>
    public int NeedLevel { get; private set; }

    public const int __ID__ = -731405630;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<Type, IConfigSingleton> _tables)
    {
        
        
        
        
        
        
        PostResolve();
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "itemConfigId:" + ItemConfigId + ","
        + "productionTime:" + ProductionTime + ","
        + "materialId:" + MaterialId + ","
        + "materialCount:" + MaterialCount + ","
        + "needLevel:" + NeedLevel + ","
        + "}";
    }
}

}

