
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using ET.Luban;


namespace ET
{

public sealed partial class ServerInfoConfig: Luban.BeanBase
{

    public ServerInfoConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ServerName = _buf.ReadString();
        PostInit();
    }

    public static ServerInfoConfig DeserializeServerInfoConfig(ByteBuf _buf)
    {
        return new ServerInfoConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; }
    /// <summary>
    /// 区服名称
    /// </summary>
    public string ServerName { get; }

    public const int __ID__ = -1669631661;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<Type, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "serverName:" + ServerName + ","
        + "}";
    }
}

}

