
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using ET.Luban;


namespace ET
{

public sealed partial class StartMachineConfig: Luban.BeanBase
{
    public StartMachineConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        InnerIP = _buf.ReadString();
        OuterIP = _buf.ReadString();
        WatcherPort = _buf.ReadString();
        PostInit();
    }

    public static StartMachineConfig DeserializeStartMachineConfig(ByteBuf _buf)
    {
        return new StartMachineConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 内网地址
    /// </summary>
    public string InnerIP { get; private set; }
    /// <summary>
    /// 外网地址
    /// </summary>
    public string OuterIP { get; private set; }
    /// <summary>
    /// 守护进程端口
    /// </summary>
    public string WatcherPort { get; private set; }

    public const int __ID__ = 1628109127;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<Type, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "innerIP:" + InnerIP + ","
        + "outerIP:" + OuterIP + ","
        + "watcherPort:" + WatcherPort + ","
        + "}";
    }
}

}

