
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using ET.Luban;


namespace ET
{

public sealed partial class TaskActionConfig: Luban.BeanBase
{

    public TaskActionConfig(ByteBuf _buf) 
    {
        TargetType = (TaskTargetType)_buf.ReadInt();
        ProcessAction = (TaskProgressType)_buf.ReadInt();
        PostInit();
    }

    public static TaskActionConfig DeserializeTaskActionConfig(ByteBuf _buf)
    {
        return new TaskActionConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public TaskTargetType TargetType { get; }
    /// <summary>
    /// 任务进度更新行为
    /// </summary>
    public TaskProgressType ProcessAction { get; }

    public const int __ID__ = 2139003741;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<Type, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public override string ToString()
    {
        return "{ "
        + "targetType:" + TargetType + ","
        + "processAction:" + ProcessAction + ","
        + "}";
    }
}

}

