
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using ET.Luban;


namespace ET
{

public sealed partial class TaskReward: Luban.BeanBase
{

    public TaskReward(ByteBuf _buf) 
    {
        ItemId = _buf.ReadInt();
        Count = _buf.ReadInt();
        PostInit();
    }

    public static TaskReward DeserializeTaskReward(ByteBuf _buf)
    {
        return new TaskReward(_buf);
    }

    /// <summary>
    /// 道具Id
    /// </summary>
    public int ItemId { get; }
    /// <summary>
    /// 数量
    /// </summary>
    public int Count { get; }

    public const int __ID__ = -1373809356;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<Type, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public override string ToString()
    {
        return "{ "
        + "ItemId:" + ItemId + ","
        + "Count:" + Count + ","
        + "}";
    }
}

}

