
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using ET.Luban;


namespace ET
{

public sealed partial class UnitConfig: Luban.BeanBase
{

    public UnitConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        UnitType = (UnitType)_buf.ReadInt();
        Class = (RoleClass)_buf.ReadInt();
        Prefab = _buf.ReadString();
        Desc = _buf.ReadString();
        AIType = _buf.ReadString();
        Height = _buf.ReadLong();
        Radius = _buf.ReadLong();
        Speed = _buf.ReadInt();
        MaxHp = _buf.ReadLong();
        MaxMp = _buf.ReadLong();
        GrowthStr = _buf.ReadLong();
        GrowthInt = _buf.ReadLong();
        GrowthAgi = _buf.ReadLong();
        STR = _buf.ReadLong();
        INT = _buf.ReadLong();
        DEX = _buf.ReadLong();
        AD = _buf.ReadLong();
        AP = _buf.ReadLong();
        DEF = _buf.ReadLong();
        MDEF = _buf.ReadLong();
        SPD = _buf.ReadLong();
        CRI = _buf.ReadLong();
        PostInit();
    }

    public static UnitConfig DeserializeUnitConfig(ByteBuf _buf)
    {
        return new UnitConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public int Id { get; }
    public string Name { get; }
    /// <summary>
    /// 类型
    /// </summary>
    public UnitType UnitType { get; }
    /// <summary>
    /// 职业
    /// </summary>
    public RoleClass Class { get; }
    /// <summary>
    /// 模型资源
    /// </summary>
    public string Prefab { get; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc { get; }
    /// <summary>
    /// AI策略
    /// </summary>
    public string AIType { get; }
    /// <summary>
    /// 身高(单位:0.1毫米)
    /// </summary>
    public long Height { get; }
    /// <summary>
    /// 体积半径
    /// </summary>
    public long Radius { get; }
    /// <summary>
    /// 速度
    /// </summary>
    public int Speed { get; }
    /// <summary>
    /// 生命
    /// </summary>
    public long MaxHp { get; }
    /// <summary>
    /// 法力
    /// </summary>
    public long MaxMp { get; }
    /// <summary>
    /// 力量成长
    /// </summary>
    public long GrowthStr { get; }
    /// <summary>
    /// 智力成长
    /// </summary>
    public long GrowthInt { get; }
    /// <summary>
    /// 敏捷成长
    /// </summary>
    public long GrowthAgi { get; }
    /// <summary>
    /// 力量
    /// </summary>
    public long STR { get; }
    /// <summary>
    /// 智力
    /// </summary>
    public long INT { get; }
    /// <summary>
    /// 敏捷
    /// </summary>
    public long DEX { get; }
    /// <summary>
    /// 物理攻击
    /// </summary>
    public long AD { get; }
    /// <summary>
    /// 法术攻击
    /// </summary>
    public long AP { get; }
    /// <summary>
    /// 物理防御
    /// </summary>
    public long DEF { get; }
    /// <summary>
    /// 法术防御
    /// </summary>
    public long MDEF { get; }
    /// <summary>
    /// 攻击速度
    /// </summary>
    public long SPD { get; }
    /// <summary>
    /// 暴击概率(1/10000)
    /// </summary>
    public long CRI { get; }

    public const int __ID__ = -568528378;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<Type, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "unitType:" + UnitType + ","
        + "class:" + Class + ","
        + "prefab:" + Prefab + ","
        + "desc:" + Desc + ","
        + "aIType:" + AIType + ","
        + "height:" + Height + ","
        + "radius:" + Radius + ","
        + "speed:" + Speed + ","
        + "maxHp:" + MaxHp + ","
        + "maxMp:" + MaxMp + ","
        + "growthStr:" + GrowthStr + ","
        + "growthInt:" + GrowthInt + ","
        + "growthAgi:" + GrowthAgi + ","
        + "STR:" + STR + ","
        + "INT:" + INT + ","
        + "DEX:" + DEX + ","
        + "AD:" + AD + ","
        + "AP:" + AP + ","
        + "DEF:" + DEF + ","
        + "MDEF:" + MDEF + ","
        + "SPD:" + SPD + ","
        + "CRI:" + CRI + ","
        + "}";
    }
}

}

