
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using ET.Luban;


namespace ET.Client
{

public sealed partial class AIConfig: Luban.BeanBase
{

    public AIConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        AIConfigID = _buf.ReadInt();
        Order = _buf.ReadInt();
        Name = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);NodeParam = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); NodeParam.Add(_e0);}}
        PostInit();
    }

    public static AIConfig DeserializeAIConfig(ByteBuf _buf)
    {
        return new AIConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; }
    /// <summary>
    /// 所属ai
    /// </summary>
    public int AIConfigID { get; }
    /// <summary>
    /// 此ai中的顺序
    /// </summary>
    public int Order { get; }
    /// <summary>
    /// 节点名字
    /// </summary>
    public string Name { get; }
    /// <summary>
    /// 节点参数
    /// </summary>
    public System.Collections.Generic.List<int> NodeParam { get; }

    public const int __ID__ = -294143606;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<Type, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "aIConfigID:" + AIConfigID + ","
        + "order:" + Order + ","
        + "name:" + Name + ","
        + "nodeParam:" + Luban.StringUtil.CollectionToString(NodeParam) + ","
        + "}";
    }
}

}

