
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET.Client
{ 
    /// <summary>
    /// 装备位置
    /// </summary>
    public enum EquipPosition
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 头盔
        /// </summary>
        Helmet = 1,
        /// <summary>
        /// 衣服
        /// </summary>
        Cloth = 2,
        /// <summary>
        /// 鞋子
        /// </summary>
        Shoe = 3,
        /// <summary>
        /// 护肩
        /// </summary>
        Shoulder = 4,
        /// <summary>
        /// 武器
        /// </summary>
        Weapon = 5,
        /// <summary>
        /// 副手
        /// </summary>
        OffHands = 6,
        /// <summary>
        /// 裤子
        /// </summary>
        Pants = 7,
    }

} 

