
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET.Client
{ 
    /// <summary>
    /// 道具类型
    /// </summary>
    public enum ItemType
    {
        /// <summary>
        /// 全部
        /// </summary>
        All = 0,
        /// <summary>
        /// 装备
        /// </summary>
        Equip = 1,
        /// <summary>
        /// 消耗品
        /// </summary>
        Consumable = 2,
        /// <summary>
        /// 材料
        /// </summary>
        Material = 3,
        /// <summary>
        /// 坐骑
        /// </summary>
        Rider = 4,
    }

} 

