
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using ET.Luban;


namespace ET.Client
{

public sealed partial class PlayerLevelConfig: Luban.BeanBase
{
    public PlayerLevelConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        NeedExp = _buf.ReadLong();
        PostInit();
    }

    public static PlayerLevelConfig DeserializePlayerLevelConfig(ByteBuf _buf)
    {
        return new PlayerLevelConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 所需经验值
    /// </summary>
    public long NeedExp { get; private set; }

    public const int __ID__ = 1701428773;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<Type, IConfigSingleton> _tables)
    {
        
        
        PostResolve();
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "needExp:" + NeedExp + ","
        + "}";
    }
}

}

