
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{ 
    public enum TaskTargetType
    {
        None = 0,
        
        Kill = 1,
        
        Item = 2,
        
        Dialogue = 3,
        
        UpLevel = 4,
        
    }

} 

