
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using ET.Luban;


namespace ET.Client
{

public sealed partial class TaskConfig: Luban.BeanBase
{
    public TaskConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        TaskName = _buf.ReadString();
        TaskDesc = _buf.ReadString();
        TaskActionType = _buf.ReadInt();
        TaskTargetId = _buf.ReadInt();
        TaskTargetCount = _buf.ReadInt();
        TaskBefore = _buf.ReadInt();
        RewardGold = _buf.ReadInt();
        PostInit();
    }

    public static TaskConfig DeserializeTaskConfig(ByteBuf _buf)
    {
        return new TaskConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 任务名字
    /// </summary>
    public string TaskName { get; private set; }
    /// <summary>
    /// 任务描述
    /// </summary>
    public string TaskDesc { get; private set; }
    /// <summary>
    /// 任务行为类型
    /// </summary>
    public int TaskActionType { get; private set; }
    /// <summary>
    /// 任务目标Id
    /// </summary>
    public int TaskTargetId { get; private set; }
    /// <summary>
    /// 任务目标数量
    /// </summary>
    public int TaskTargetCount { get; private set; }
    /// <summary>
    /// 前置任务ID
    /// </summary>
    public int TaskBefore { get; private set; }
    /// <summary>
    /// 任务奖励金币数量
    /// </summary>
    public int RewardGold { get; private set; }

    public const int __ID__ = -1794275001;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<Type, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "taskName:" + TaskName + ","
        + "taskDesc:" + TaskDesc + ","
        + "taskActionType:" + TaskActionType + ","
        + "taskTargetId:" + TaskTargetId + ","
        + "taskTargetCount:" + TaskTargetCount + ","
        + "taskBefore:" + TaskBefore + ","
        + "rewardGold:" + RewardGold + ","
        + "}";
    }
}

}

