
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET.Client
{ 
    public enum TaskProgressType
    {
        Add = 0,
        
        Sub = 1,
        
        Update = 2,
        
    }

} 

