
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using ET.Luban;


namespace ET.Client
{
[Config]
public partial class TGlobalConfigCategory: ConfigSingleton<TGlobalConfigCategory>
{

     private readonly TGlobalConfig _data;

    public TGlobalConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = TGlobalConfig.DeserializeTGlobalConfig(_buf);
        PostInit();
    }


    /// <summary>
    /// 背包容量上限
    /// </summary>
     public int BagCapacityLimit => _data.BagCapacityLimit;
    /// <summary>
    /// 背包起始容量
    /// </summary>
     public int BagCapacityStart => _data.BagCapacityStart;

    public override void Resolve(Dictionary<Type, IConfigSingleton> tables)
    {
        _data.Resolve(tables);
        PostResolve();
    }
    public override string ConfigName() => nameof (TGlobalConfig);
}
}
