
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Luban;


namespace ET.Client
{

public sealed partial class TGlobalConfig: Luban.BeanBase
{
    public TGlobalConfig(ByteBuf _buf) 
    {
        BagCapacityLimit = _buf.ReadInt();
        BagCapacityStart = _buf.ReadInt();
        PostInit();
    }

    public static TGlobalConfig DeserializeTGlobalConfig(ByteBuf _buf)
    {
        return new TGlobalConfig(_buf);
    }

    /// <summary>
    /// 背包容量上限
    /// </summary>
    public int BagCapacityLimit { get; private set; }
    /// <summary>
    /// 背包起始容量
    /// </summary>
    public int BagCapacityStart { get; private set; }

    public const int __ID__ = 165700409;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<Type, IConfigSingleton> _tables)
    {
        
        
        PostResolve();
    }

    public override string ToString()
    {
        return "{ "
        + "bagCapacityLimit:" + BagCapacityLimit + ","
        + "bagCapacityStart:" + BagCapacityStart + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}

